# Generated by Django 2.0.6 on 2019-11-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cur_number', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_counter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TGuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('guru_status', models.CharField(blank=True, max_length=255, null=True)),
                ('guru_pic_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_guru',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_lesson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('user_status', models.CharField(blank=True, max_length=255, null=True)),
                ('portrait_url', models.ImageField(blank=True, null=True, upload_to='user_portrait')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('sign', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TAlbumList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(blank=True, max_length=255, null=True)),
                ('album_info', models.TextField(blank=True, null=True)),
                ('album_author', models.IntegerField(blank=True, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('album_status', models.CharField(blank=True, max_length=255, null=True)),
                ('stars', models.CharField(blank=True, max_length=255, null=True)),
                ('speaker_id', models.IntegerField(blank=True, null=True)),
                ('episode_number', models.CharField(blank=True, max_length=255, null=True)),
                ('content_brief', models.TextField(blank=True, null=True)),
                ('album_pic_url', models.ImageField(blank=True, null=True, upload_to='album')),
            ],
            options={
                'db_table': 't_album_list',
            },
        ),
        migrations.CreateModel(
            name='TArticleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author_id', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('cate', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('article_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_article_list',
            },
        ),
        migrations.CreateModel(
            name='TArticlePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='article_pic')),
            ],
            options={
                'db_table': 't_article_pic',
            },
        ),
        migrations.CreateModel(
            name='TAudioList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.CharField(blank=True, max_length=255, null=True)),
                ('album_id', models.IntegerField(blank=True, null=True)),
                ('audio_url', models.FileField(blank=True, null=True, upload_to='audio')),
                ('audio_time', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_size', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_audio_list',
            },
        ),
        migrations.CreateModel(
            name='TCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(blank=True, max_length=255, null=True)),
                ('img_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('img_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_carousel',
            },
        ),
    ]
