# Generated by Django 2.0.6 on 2019-11-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='权限名称')),
                ('url', models.CharField(max_length=255, verbose_name='请求路径')),
                ('level', models.IntegerField(verbose_name='请求等级')),
                ('parent_id', models.IntegerField(verbose_name='上级id ')),
            ],
            options={
                'db_table': 't_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='角色名称')),
                ('permission', models.ManyToManyField(blank=True, to='authority.Permission', verbose_name='角色对应权限')),
            ],
            options={
                'db_table': 't_role',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='人员名称')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('role', models.ManyToManyField(blank=True, to='authority.Role', verbose_name='职员角色')),
            ],
            options={
                'db_table': 't_staff',
            },
        ),
    ]
