# Generated by Django 2.0.6 on 2019-11-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_menu',
            field=models.BooleanField(default='0', verbose_name='是否是菜单'),
        ),
    ]
